apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: twitter-feed-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: twitter-feed-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/twitter-feed
      property: db_pass
  - secretKey: dbUser
    remoteRef:
      key: secret/twitter-feed
      property: db_user
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/twitter-feed
      property: key_base
  - secretKey: twitterConsumerKey
    remoteRef:
      key: secret/twitter-feed
      property: twitter_consumer_key
  - secretKey: twitterConsumerSecret
    remoteRef:
      key: secret/twitter-feed
      property: twitter_consumer_secret
  - secretKey: twitterAccessToken
    remoteRef:
      key: secret/twitter-feed
      property: twitter_access_token
  - secretKey: twitterAccessTokenSecret
    remoteRef:
      key: secret/twitter-feed
      property: twitter_access_token_secret