version: v1.0
name: TwitterFeed deployment pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
blocks:
  - name: Deploy
    task:
      env_vars:
        - name: NAMESPACE
          value: "twitter-feed"
      secrets:
        - name: j-cluster-k8s
      jobs:
        - name: deploy
          commands:
            - cache restore k8s-$SEMAPHORE_WORKFLOW_ID
            - chmod 0600 ~/j-cluster-kubeconfig.yaml
            - export KUBECONFIG=~/j-cluster-kubeconfig.yaml
            - kubectl -n $NAMESPACE apply -f k8s/secrets.yml
            - kubectl -n $NAMESPACE apply -f k8s/deployment.yml
            - kubectl -n $NAMESPACE apply -f k8s/ingress.yml
            - kubectl -n $NAMESPACE apply -f k8s/monitoring.yml
            - kubectl -n $NAMESPACE rollout restart deployment twitter-feed
